blog/urls.py
from django.conf.urls import url
from blog import views

urlpatterns = [
        url(r'^$', views.blog, name='blog'),
        url(r'^(?P<post_id>[0-9]+)/$', views.post, name='post')
]

main/urls.py
from django.conf.urls import url
from main import views
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from svitla import settings

urlpatterns = [
        url(r'^$', views.index, name='index'),
        url(r'^info/$', views.info, name='info'),
        url(r'^about/$', views.about, name='about'),
        url(r'^contact/$', views.contact, name='contact'),
        url(r'^FAQ/$', views.faq, name='faq'),
        url(r'^price/$', views.price, name='price'),
        url(r'^add_recall/$', views.add_recall, name='add_reall'),
        url(r'^add_recall/ok$', views.form_valid_ok, name='add_form_ok'),
        url(r'^price-wedding/$', views.price_wedding, name='price-wedding'),
        url(r'^price-portret/$', views.price_portret, name='price-portret'),
        url(r'^categories/(?P<type_foto>[\w\-]+)/$', views.categories, name='categories'),
        url(r'^categories/([\w\-]+)/(?P<album_id>[0-9]+)/$', views.albums, name='album')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

svitla/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls', namespace='main')),

]

bid_works/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    #image_save_url = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),"static/images/album_cover")

    name = models.CharField(max_length=128, unique=True)
    description = models.CharField(max_length=500)
    data = models.DateField(auto_now=True)
    cover = models.ImageField(upload_to="blog/cover")
    text = models.CharField(max_length=10000)

    def __str__ (self):
        return self.name

main/models.py
import os

from datetime import date
from django.db import models


# -*- coding: utf-8 -*-
class Album(models.Model):
    # -*- coding: utf-8 -*-
    CATEGORIES_PHOTO_ALBUM = (
        ("Wedding", "Свадьба"),
        ("Portrait", "Портрет"),
        ("Family-photo", "Семейное фото"),
        ("Love-Story", "Love Story")
    )
    #image_save_url = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),"static/images/album_cover")





    name = models.CharField(max_length=128, unique=True)
    description = models.CharField(max_length=500)
    data = models.DateField(auto_now=True)

    location = models.CharField(max_length=100)
    categories = models.CharField(max_length=20, choices=CATEGORIES_PHOTO_ALBUM, default="Свадьба")
    cover = models.ImageField(upload_to="photo/cover")

    def __str__ (self):
        return self.name



class Foto(models.Model):

    album = models.ForeignKey(Album)
    photo = models.ImageField(upload_to="photo")
    horizontal = models.BooleanField(default=False)

    def __str__ (self):
        return u'%s/%s' % (self.album.name, self.id)
 # -*- coding: utf-8 -*-
class Recall(models.Model):
    # -*- coding: utf-8 -*-
    CATEGORIES_PHOTO_TYPE = (
        ("Wedding", "свадебная"),
        ("Pregnancy", "беременность"),
        ("Family-photo", "семейная/детская"),
        ("Love-Story", "love story"),
        ("Other", "другая")
    )
    name = models.CharField(max_length=30)
    email = models.EmailField()
    social = models.URLField()
    type_photo = models.CharField(max_length=20, choices=CATEGORIES_PHOTO_TYPE, default='свадебная')
    location = models.CharField(max_length=30)
    massage = models.CharField(max_length=1000)
    date_photo_shooting = models.DateField()
    info_about_my = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class SliderPhoto(models.Model):
    photo = models.ImageField(upload_to='slider')

recall/models.py
from django.db import models

# Create your models here.

main/forms.py
from django.forms import ModelForm, DateInput, Textarea
from main.models import Recall

class RecallForm(ModelForm):

    class Meta:
        model = Recall
        fields = ['name','email', 'social', 'type_photo', 'location', 'date_photo_shooting', 'massage', 'info_about_my']
        widgets = {
            'date_photo_shooting': DateInput(format='%d/%m/%Y'),
            'massage' : Textarea()
        }

bid_works/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.shortcuts import render
from blog.models import Post

context_dict = {}
post_list = {}
def blog(request):
    posts_list = Post.objects.filter()
    context_dict['posts'] = posts_list
    return render(request, 'blog/blog.html', context_dict)

def post(request, post_id):
    post = Post.objects.get(id=post_id)
    post_list['post'] = post
    return render(request, 'blog/post.html', post_list)

main/views.py
from django.shortcuts import render
from main.models import Album, Foto, SliderPhoto
from  main.forms import RecallForm
from main.Utilits.paginatorManager import PaginatorManager


context_dict = {}
foto_dict = {}
slider_context = {}
album_id = 0

def index(request):
    slide_list = SliderPhoto.objects.filter()
    slider_context["slides"] = slide_list
    return render(request, 'main/index.html', slider_context)

def info(request):
    return render(request,'main/info.html')

def about(request):
    return render(request, 'main/about.html')

def contact(request):
    return render(request, 'main/contact.html')

def faq(request):
    return render(request, 'main/faq.html')

def price(request):
    return render(request, 'main/price.html')

def categories(request, type_foto):
    album_list = Album.objects.filter(categories=type_foto)
    context_dict['album'] = album_list
    context_dict['title'] = album_list[0].categories
    return render(request, 'main/categories.html', context_dict)

def albums(request, album_id):
    album = Album.objects.get(id=album_id)
    foto_dict['photos'] = Foto.objects.filter(album=album)
    foto_dict['album_info'] = album
    pm = PaginatorManager()
    foto_dict['next'] = pm.next(Album, album_id)
    foto_dict['previous'] = pm.previous(Album, album_id)
    return render(request, 'main/albums.html', foto_dict)

def add_recall(request):
    if request.method == 'POST':
        form = RecallForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'main/form_valid_ok.html')
    else:
        form = RecallForm()
    return render(request, 'main/add_recall.html', {'form' : form})

def form_valid_ok(request):
    return render(request, 'main/form_valid_ok.html')

def price_wedding(request):
    return render(request, 'main/price-wedding.html')

def price_portret(request):
    return render(request, 'main/price-portret.html')

recall/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>

 {% load staticfiles %}
<html lang="en">
  <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Great+Vibes">
       <link rel="stylesheet" href="http://getbootstrap.com/dist/css/bootstrap.min.css" >
       <link rel="stylesheet" href="http://getbootstrap.com/examples/dashboard/dashboard.css" >
      <link href="https://fonts.googleapis.com/css?family=Comfortaa:300,400,700|Cormorant+Garamond:300,300i,400,400i,500,500i,600,600i,700,700i|Fira+Sans+Condensed:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i|Old+Standard+TT:400,400i,700|Philosopher:400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Poiret+One|Questrial|Varela&amp;subset=cyrillic,latin-ext" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Arsenal" rel="stylesheet">
      <link rel="stylesheet" href="{% static 'skdslider-master/src/css/main.css' %}">
       <link rel="stylesheet" href="{% static 'boxLoader-Jquery-Plugin-master/css/main.css' %}">
       <link rel="stylesheet" href="{% static 'boxLoader-Jquery-Plugin-master/css/normalize.css' %}">
       <link rel="stylesheet" href="{% static 'boxLoader-Jquery-Plugin-master/fonts/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="stylesheet" href="{% static 'css/font.css' %}">

  </head>
  <body>
   <!-- Header -->
    <header class="header">
          <!-- Logo -->
          <div class="logo">
                <a href="/" name="top"><div class="logo-img"></div></a>
          </div>
          <!-- Menu -->
          <div class="mainWrap">
		        <a id="touch-menu" class="mobile-menu" href="/"><span class="icon-reorder"></span></a>
		        <nav>
			        <ul class="menu">
				        <li>
					        <a href=""><i class="icon-home"></i>PORTFOLIO</a>
					        <ul class="sub-menu">
						        <li><a href="/categories/Wedding/">Wedding</a></li>
						        <li><a href="/categories/Love-Story/">Love story</a></li>
						        <li><a href="/categories/Family-photo/">Family</a></li>
						        <li><a href="/categories/Portrait/">Portret</a></li>
					        </ul>
				        </li>
				        <li>
					        <a  href="{% url 'main:about' %}"><i class="icon-user"></i>ABOUT</a>
				        </li>
				        <li>
					        <a  href="#"><i class="icon-bullhorn"></i>INFO</a>
                            <ul class="sub-menu">
						        <li><a href="{% url 'main:price' %}">Price</a></li>
						        <li><a href="{% url 'main:faq' %}">FAQ</a></li>
                            </ul>
				        </li>
				        <li>
					        <a  href="{% url 'main:add_reall' %}"><i class="icon-envelope-alt"></i>CONTACT</a>
				        </li>
			        </ul>
		        </nav>
          </div><!--end mainWrap-->
    </header>
   <!-- Site content -->

        {% block body_block %}{% endblock %}

   <!-- Footer-->
    <footer class="footer">
        <div class="container">
            <div class="row">
                 <div class="contact-info col-md-4" >
                    <p class="text-center">photosvitla@gmail.com</p>
                    <p class="text-center">+38(095)85-58-186</p>
                </div>
                <div class="footer-logo col-md-4">
                </div>
                <div class="social col-md-4">
                    <p>follow me on</p>
                    <a href="https://www.instagram.com/svitla_photo/" target="_blank"><img src="{% static 'images/i.png' %}"></a>
                    <a href="https://vk.com/svitla_photo" target="_blank"><img src="{% static 'images/vk.png' %}"></a>
                    <a href="https://www.facebook.com/svitla.photo" target="_blank"><img src="{% static 'images/f.png' %}"></a>
                    <a href="https://mywed.com/en/photographer/svitla/" target="_blank"><img src="{% static 'images/mv.png' %}"></a>
                </div>

            </div>
        </div>
    </footer>
      <div class="button_ton" id="top">
   </div>


       <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
       <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
       <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
       <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
       <script src="{% static 'skdslider-master/src/js/skdslider.js' %}"></script>
       <script src="{% static 'skdslider-master/src/js/main.js' %}"></script>
       <script src="{% static 'boxLoader-Jquery-Plugin-master/js/main.js' %}"></script>
       <script src="{% static 'boxLoader-Jquery-Plugin-master/js/jquery.boxloader.min.js' %}"></script>
       <script src="{% static 'js/parallax.js' %}"></script>
       <script src="{% static 'js/parallax_main.js' %}"></script>
       <script src="{% static 'js/toch.js' %}"></script>
       <script src="{% static 'js/menu.js' %}"></script>
       <script src="{% static 'js/main.js' %}"></script>
       <script src="{% static 'js/button _top.js' %}"></script>
  </body>
</html>

templates/blog/blog.html
{% extends "base.html" %}

{% load staticfiles %}

{% block body_block %}

    {% if posts %}
        <div class="container blog">
        <div class="row">
                {% for post in posts %}
                     <a href="/blog/{{ post.id }}/">
                        <div class="post-preview col-md-4" >
                            <div class="col-md-6">
                                <div class="cover">
                                    <div class="check">
                                    </div>

                                    </div>
                                </div>
                        </div>
                         <div class="col-md-6">
                                <div class="description">
                                    <h3>{{ post.name }}</h3>
                                    <p>{{ post.description }}</p>
                                </div>
                         </div>
                      </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}


{% endblock %}

templates/blog/post.html
{% extends "base.html" %}

{% load staticfiles %}

{% block body_block %}

    {% if post %}

                <header>
                    <h2>{{ post.name }}</h2>
                    <p>{{ post.data }}</p>
                </header>
                <section>
                    <img src="{{ post.cover.url }}">
                    <p> {{ post.text }}</p>
                </section>
            </a>

    {% else %}

post
    {% endif %}

{% endblock %}

templates/main/about.html
{% extends "base.html" %}

{% load staticfiles %}

{% block body_block%}

<section class="section parallax parallax-1">
  <div class="cont">
    <h1>~ About ~</h1>
  </div>
</section>

<section class="section content">
    <div class="about">
      <div class="container">
                  <div class="row">
                      <div class="categorie">
                          <div class="col-md-6 ">
                            <div class="thumbnail">
                                <img src="{% static 'images/about-photo.jpg' %}">
                            </div>
                          </div>
                          <div class="col-md-6">
                              <p>Привет! Я рада, что Вы зашли на мой сайт. Меня зовут Юлия Свитла.
                                  Я свадебный и портретный фотограф, влюблена в мягкий естественный свет и настоящие, живые эмоции.
                                  Живу в Киеве, фотографирую по всей Украине. Снимаю в стиле Fine Art на цифровую камеру.
                                  Своими фотоработами стараюсь рассказать трогательные, чувственные и наполненные любви истории моих клиентов.
                                  Я люблю свое дело и рада работать с людьми, увлеченными тем, чтобы сделать их воспоминания нежными и утонченными!
                                  Поэтому отдаю предпочтение стильным и уютным свадьбам со сборами невесты, красивыми выездными регистрациями, флористикой и декором.
                              </p>
                               <p>Если Вы находитесь в поиске своего фотографа и Вам интересно и близко то, что я делаю - напишите мне сообщение
                                   через <a href="/add_recall/">форму</a> на сайте или свяжитесь любым другим способом, и я отвечу на все ваши вопросы.
                                   Улыбайтесь! Солнечного Вам настроения!
                               </p>
                          </div>
                      </div>
                  </div>
      </div>
    </div>
</section>
{% endblock %}

templates/main/add_recall.html
{% extends "main/contact.html" %}

{% load staticfiles %}

{% block form_block %}
        <div class="contact">


                <p class="text-center">
                                  Благодарю за Ваш интерес к моим работам! А теперь, время рассказать подробнее о Вашем предстоящем событии
                                  (организатор, время, место, стиль и т.д.). Вы всегда можете отправить мне сообщение через Viber,
                                  СМС или соц.сети. А также через форму для связи ниже на этой странице.
                                  Так же, я буду рада, если Вы напишете несколько слов о себе, своей паре, о том,
                                  какой представляете вашу фотосессию и что ожидаете от нее. Не ограничивай себя в описании деталей,
                                  ведь это частичка того, что сделает ваше событие незабываемым!Спасибо!
                </p>
    </div>
    <div class="form-recall form">
        <div class="container">
            <div class="row">
                        <div class="col-md-6">
                <div class="form-img">
                </div>
            </div>
                <div class="col-md-6">
                    <form id="recall_form" method="POST" action="/add_recall/" class="form-horizontal" role="form">
                        {% csrf_token %}
                         <div class="form-group">
                            <label for="{{ form.name.id_for_label }}" class=" control-label">Имя</label>
                                <p class="errors"> {{ form.name.errors }}</p>
                                {{ form.name }}
                                {% if form.name.help_text %}
                                    <p class="help">{{ form.name.help_text|safe }}</p>
                                {% endif %}
                            </div>
                        <div class="form-group">
                            <label for="{{ form.email.id_for_label }}l" class="control-label">E-mail</label>
                                <p class="errors">{{ form.email.errors }}</p>
                                {{ form.email }}
                                {% if form.email.help_text %}
                                    <p class="help">{{ form.email.help_text|safe }}</p>
                                {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="{{ form.type_photo.id_for_label }}" class="control-label">Какая съемка Вас интересует?</label>
                                <p class="errors">{{ form.type_photo.errors }}</p>
                                {{ form.type_photo }}
                                {% if form.type_photo.help_text %}
                                    <p class="help">{{ form.type_photo.help_text|safe }}</p>
                                {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="{{ form.date_photo_shooting.id_for_label }}" class=" control-label">Планируемая дата съемки </label>
                                <p class="errors">{{ form.date_photo_shooting.errors }}</p>
                                {{ form.date_photo_shooting }}
                                {% if form.date_photo_shooting.help_text %}
                                    <p class="help">{{ form.date_photo_shooting.help_text|safe }}</p>
                                {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="{{ form.location.id_for_label }}" class=" control-label">Планируемое место съемки </label>
                                <p class="errors">{{ form.location.errors }}</p>
                                {{ form.location }}
                                {% if form.location.help_text %}
                                    <p class="help">{{ form.location.help_text|safe }}</p>
                                {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="{{ form.massage.id_for_label }}" class=" control-label">Сообщение</label>
                                <p class="errors">{{ form.massage.errors }}</p>
                                {{ form.massage }}
                                {% if form.massage.help_text %}
                                    <p class="help">{{ form.massage.help_text|safe }}</p>
                                {% endif %}
                        </div>
                         <div class="form-group">
                            <label for="{{ form.social.id_for_label }}" class=" control-label">Cсылка на Вашу страницу в соц. сетях</label>
                                <p class="errors">{{ form.social.errors }}</p>
                                {{ form.social }}
                                {% if form.social.help_text %}
                                    <p class="help">{{ form.social.help_text|safe }}</p>
                                {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="{{ form.info_about_my.id_for_label }}" class=" control-label">Как Вы обо мне узнали (Google, друзья, соц.сеть и т.д.)? *</label>
                                <p class="errors">{{ form.info_about_my.errors }}</p>
                                {{ form.info_about_my }}
                                {% if form.info_about_my.help_text %}
                                    <p class="help">{{ form.info_about_my.help_text|safe }}</p>
                                {% endif %}
                            </div>
                        <div class="form-group">
                            <div class="">
                                <button type="submit" class="btn btn-default btn-lg">Отправить</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/main/albums.html
{% extends "base.html" %}

{% load staticfiles %}

{% block body_block %}

    {% if photos %}
    <div class="categories">
              <div class="container">
                  <div class="row">
    {% for photo in photos %}
        {% if photo.horizontal == False %}
                      <div class="categorie">
                          <div class="col-md-6 photo">
                            <div class="thumbnail photo">
                                <img src="{{ photo.photo.url  }}" alt="эскиз">
                            </div>
                          </div>
                      </div>
        {% else %}
                      <div class="categorie">
                          <div class="col-md-12 photo">
                            <div class="thumbnail">
                                <img src="{{ photo.photo.url  }}" alt="эскиз">
                            </div>
                          </div>
                      </div>
        {% endif %}
    {% endfor %}
                  </div>
              </div>
        </div>
    {% else %}
      <p>Такого альбома не найдено. Попробуйте еще ;)</p>
    {% endif %}



    <div class="next-page">
    {% if next %}
         <a href="/categories/{{ album_info.categories }}/{{ next }}/"> &lt;&lt;Back </a>
    {% endif %}


      {% if previous %}
          <a href="/categories/{{ album_info.categories }}/{{ previous }}/">Next>></a>
    {% endif %}

    </div>

{% endblock %}

templates/main/categories.html
{% extends "base.html" %}

{% load staticfiles %}

{% block body_block %}

    {% if album %}


    <div class="categories">
              <div class="container container-photo">
                  <div class="row">
    {% for category in album %}
                      <a href="/categories/{{ category.categories }}/{{ category.id }}/">
                      <div class="categorie">
                          <div class="col-md-4">
                            <div class="thumbnail check">
                                <img src="{{ category.cover.url  }}" alt="эскиз">
                                <div class="caption">
                                    <h3>{{ category.name }}</h3>
                                </div>
                            </div>
                          </div>
                      </div>
                      </a>
    {% endfor %}
                  </div>
              </div>
        </div>
    {% else %}
      <p>Такой категории не найдено. Попробуйте еще ;)</p>
    {% endif %}

{% endblock %}

templates/main/contact.html
{% extends "base.html" %}

{% load staticfiles %}

{% block body_block %}



    {% block form_block %}{% endblock %}
{% endblock %}

templates/main/faq.html
{% extends "base.html" %}

{% load staticfiles %}

{% block body_block %}

     </div>
    <div class="FAQ">
        <div class="container container-photo">
            <div class="row">
                <div class="col-md-offset-1 col-md-10">
                    <p class="question">Когда и как лучше бронировать дату для фотосъемки?</p>
                </div>
                <div class="col-md-offset-1 col-md-10">
                    <p class="answer">
                        Если речь идет о свадебной съемке, то я советую сразу после уточнения предполагаемой даты свадьбы,
                        задуматься о выборе своего фотографа.
                        Чтобы забронировать дату, напишите мне в разделе <a href="/add_recall/">«Оставить заявку»</a> или любым удобным способом.
                        После подтверждения даты, подписания договора и внесения предоплаты, дата съемки будет забронирована за вами.
                        Предоплата вносится заранее  и составляет  30% от стоимости услуг. Вы всегда сможете встретиться со мной в уютном
                        кафе за чашечкой чая, чтобы обсудить детали, а также заключить договор. После внесения предоплаты дата считается
                        забронированной, но в случае отмены/переноса даты свадьбы после бронирования аванс не возвращается.
                        Если вы хотите семейную съёмку, love story или портретную съёмку - договор подписывать не нужно.
                        Достаточно утвердить дату съёмки и внести предоплату в размере 50%
                    </p>
                </div>
                <div class="col-md-offset-1 col-md-10">
                    <p class="question">Где вы находитесь? Выезжаете ли в другой город? </p>
                </div>
                <div class="col-md-offset-1 col-md-10">
                    <p class="answer">
                        Я живу в Киеве. Но люблю путешествовать и для съемки вашей свадьбы готова ехать в любую точку Украины.
                        Так что не стесняйтесь, напишите мне и я свяжусь с вами, чтобы уточнить все детали и возможность съемки.
                    </p>
                </div>
                <div class="col-md-offset-1 col-md-10">
                    <p class="question">Что включают в себя и сколько стоят ваши услуги на свадьбе? </p>
                </div>
                <div class="col-md-offset-1 col-md-10">
                    <p class="answer">
                        Тарифы на пакеты по свадебной съемке указаны в разделе <a href="/price/">«Цены»</a>.
                        Если ни один из тарифов вам не подошел, напишите мне, и мы найдем решение индивидуально для вашего случая.
                        Опишите, какая фотосъемка вам нужна. Я свяжусь с вами, чтобы обсудить все детали — место проведения, сроки, бюджет.
                    </p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/main/form_valid_ok.html
{% extends "main/contact.html" %}

{% load staticfiles %}

{% block form_block %}

    <div class="form-valid">
    <h3 class="text-center">Спасибо за оставленную заявку!</h3>
        <p class="text-center">Я в ближайшее время свяжусь с Вами для подтверждения и обсуждения деталей фотосъемки.
Хорошего Дня!</p>

<p class="text-center">Юлия Свитла 🙂</p>
    </div>
{% endblock %}

templates/main/index.html
{% extends "base.html" %}

{% load staticfiles %}

{% block body_block %}
    <!-- Slider -->
    {% if slides %}
    <div class="slider">
        <ul class="skdslider">
            {% for slide in slides %}
            <li>
            <img src="{{ slide.photo.url }}" alt="">
            </li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}

      <!-- Quote -->

    <div class="quote">
    <blockquote>
        <p class="quote-text">
              In every person there are bits of beauty, just need to know how to find and collect them
            together to show the whole world. For this I chose a photo. The magic of this process fascinates.
        </p>
        <cite><p class="quote-autor text-right"> Julia Svitla</p></cite>
    </blockquote>
    </div>

      <!-- Categories -->

    <div class="categories">
              <div class="container">
                  <div class="row">
                      <a href="/categories/Family-photo/">
                          <div class="col-md-3 categorie">
                            <div class="thumbnail animation-photo check">
                                <img src="../static/images/family.jpg" alt="эскиз">
                                <div class="caption text-center">
                                    <h3>Семейное фото</h3>
                                </div>
                            </div>
                          </div>
                      </a>
                      <a href="/categories/Love-Story/">
                          <div class="col-md-3 categorie">
                            <div class="thumbnail check animation-photo">
                                <img src="../static/images/LoveStory.jpg" alt="эскиз">
                                <div class="caption text-center">
                                    <h3>Love Story</h3>
                                </div>
                            </div>
                        </div>
                      </a>
                      <a href="/categories/Wedding/">
                         <div class="col-md-3 categorie">
                            <div class="thumbnail check animation-photo">
                                <img src="../static/images/wedding.jpg" alt="эскиз">
                                <div class="caption text-center">
                                    <h3>Свадьба</h3>
                                </div>
                            </div>
                         </div>
                      </a>
                      <a href="/categories/Portrait/">
                        <div class="col-md-3 categorie ">
                            <div class="thumbnail check animation-photo">
                                <img src="../static/images/port.jpg" alt="эскиз">
                                <div class="caption text-center">
                                    <h3>Портрет</h3>
                                </div>
                            </div>
                        </div>
                      </a>
                  </div>
              </div>
    </div>


{% endblock %}